Repository ocadotechnology-university/DXS, pull requests merged in 2023-04, with the labels that each got.

#9 Add dependabot to the project
  .github/dependabot.yml
Labels: enhancement

#5 Fixed sessions subpage unauthorized error, but allowed only admins to access it.
  src/main/java/com/pwr/students/config/SecurityConfiguration.java
  src/main/webapp/app/modules/account/sessions/sessions.reducer.ts
  src/main/webapp/app/modules/account/sessions/sessions.tsx
  src/main/webapp/app/shared/layout/header/header.tsx
  src/main/webapp/app/shared/layout/menus/account.tsx
Labels: bug

#10 change VERSION variable from maven to github tag (probably)
  webpack/environment.js
Labels: enhancement

#22 add build workflow when pull request created
  .github/workflows/build.yml
Labels: enhancement

#23 fix tests for session changes
  src/main/webapp/app/config/axios-interceptor.spec.ts
  src/main/webapp/app/shared/layout/menus/account.tsx
  src/test/java/com/pwr/students/web/rest/AccountResourceIT.java
Labels: bug

#25 Big update of dependencies part 1
  .github/dependabot.yml
  package-lock.json
  package.json
  pom.xml
Labels: dependencies

#37 Big update dependencies part 2
  .github/dependabot.yml
  .github/workflows/build.yml
  package-lock.json
  package.json
Labels: dependencies
